Add typescript n convert all files
JesseRWeigel/battlemath pull request #88
Opened 2022-10-04 23:37 UTC by ayrbox

2022-10-04 23:41 UTC, ayrbox commented
@JesseRWeigel 
It was my fault on earlier PR. My fork was not sync with main project. 

Let me know if any change is required. Thanks :+1:

2022-10-05 13:35 UTC, JesseRWeigel requested changes

2022-10-05 13:35 UTC, JesseRWeigel commented on package.json
> +  "name": "test-app",
Let's change this back to battlemath

2022-10-05 19:03 UTC, JesseRWeigel approved these changes

2022-10-05 19:03 UTC, JesseRWeigel commented
Looks like the conflicts are back. I merged a branch with some css changes. That may have caused it.

2022-10-07 21:08 UTC, JesseRWeigel commented
I made all the fixes for the merge conflicts but messed something up and can't update this branch. It made a new branch instead: [https://github.com/JesseRWeigel/battlemath/commit/50b74f43de96d9284ad9ad2de9dc09df4f7a2a34](https://github.com/JesseRWeigel/battlemath/commit/50b74f43de96d9284ad9ad2de9dc09df4f7a2a34)

2022-10-07 23:12 UTC, ayrbox commented
@JesseRWeigel sorry, I was not able fix the conflict early. I've fixed now. Please merge it if its good enough :)

2022-10-08 01:23 UTC, JesseRWeigel commented
Thanks @ayrbox !

2022-10-08 01:23 UTC, merged